"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Check, ChevronRight, Gift, Heart, Menu, Minus, Package, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Truck, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";

type Product = { id: number; name: string; category: string; price: number; tone: string; accent: string; tag?: string; glyph: string };
type CartItem = Product & { qty: number; personalization: string; color: string };
const products: Product[] = [
  { id: 1, name: "Copo Aurora", category: "Copos personalizados", price: 49.9, tone: "#d5a56f", accent: "#7c3f24", tag: "Mais pedido", glyph: "M" },
  { id: 2, name: "Garrafa Essência", category: "Garrafas personalizadas", price: 89.9, tone: "#947058", accent: "#f0dfc7", glyph: "A" },
  { id: 3, name: "Chaveiro Afeto", category: "Chaveiros personalizados", price: 29.9, tone: "#e7c897", accent: "#563323", glyph: "♡" },
  { id: 4, name: "Camiseta Memória", category: "Camisetas personalizadas", price: 74.9, tone: "#efe2cf", accent: "#4a291e", glyph: "L" },
  { id: 5, name: "Kit Celebração", category: "Kits personalizados", price: 159.9, tone: "#5a3427", accent: "#d8b56e", tag: "Para presentear", glyph: "✦" },
];
const money = (n:number) => n.toLocaleString("pt-BR", { style:"currency", currency:"BRL" });

export default function Home() {
  const [menu,setMenu]=useState(false), [selected,setSelected]=useState<Product|null>(null), [cartOpen,setCartOpen]=useState(false), [checkout,setCheckout]=useState(false);
  const [cart,setCart]=useState<CartItem[]>([]), [name,setName]=useState(""), [color,setColor]=useState("Chocolate"), [details,setDetails]=useState(""), [qty,setQty]=useState(1);
  const subtotal=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.qty,0),[cart]), discount=subtotal>=150?subtotal*.1:0, shipping=cart.length?15:0, total=subtotal-discount+shipping;
  const add=()=>{ if(!selected)return; setCart(c=>[...c,{...selected,qty,color,personalization:name||details||"Personalização a definir"}]); setSelected(null);setCartOpen(true);setName("");setDetails("");setQty(1); };
  return <main>
    <div className="announcement">Produção em até 5 dias úteis após aprovação <span>•</span> Frete fixo SP: R$ 15</div>
    <header className="site-header"><a className="brand" href="#inicio"><span className="brand-mark">M</span><span>Mimo <i>&</i> Arte<small>Seu estilo em cada detalhe.</small></span></a>
      <nav className={menu?"nav open":"nav"}><a href="#produtos">Produtos</a><a href="#como-funciona">Como funciona</a><a href="#presentes">Para presentear</a><a href="#contato">Contato</a></nav>
      <div className="header-actions"><button className="icon-btn search" aria-label="Buscar"><Search/></button><button className="cart-button" aria-label={`Sacola com ${cart.length} itens`} onClick={()=>setCartOpen(true)}><ShoppingBag/><span className="desktop-only">Sacola</span>{cart.length>0&&<b>{cart.length}</b>}</button><button className="icon-btn menu-btn" aria-label="Abrir menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>
    </header>
    <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow"><Sparkles/> Feito à mão, pensado para você</p><h1>Personalizados<br/><em>feitos para você.</em></h1><p className="hero-text">Transforme nomes, histórias e momentos em peças únicas — criadas com carinho em cada detalhe.</p><a className="primary-cta" href="#produtos">Personalize o seu <ArrowRight/></a><div className="hero-proof"><span><ShieldCheck/> Compra segura</span><span><Heart/> Arte aprovada por você</span></div></div>
      <div className="hero-art" aria-label="Produtos personalizados"><div className="blob one"/><div className="blob two"/><div className="product-scene bottle"><span className="cap"/><span className="monogram">M</span><small>mimo & arte</small></div><div className="product-scene cup"><span className="handle"/><span className="monogram">amor</span></div><div className="gift-card"><Gift/><span>Feito especialmente<br/><b>para alguém único</b></span></div><span className="hand-note">único, como você <Heart/></span></div>
    </section>
    <section className="trust-strip"><div><Truck/><span><b>Frete fixo em SP</b><small>R$ 15 para todo o estado</small></span></div><div><Sparkles/><span><b>Você aprova a arte</b><small>Até 2 pedidos de alteração</small></span></div><div><Package/><span><b>Produção cuidadosa</b><small>Até 5 dias úteis após aprovação</small></span></div></section>
    <section className="section products-section" id="produtos"><div className="section-heading"><div><p className="eyebrow">Escolha, imagine, personalize</p><h2>Feitos para contar <em>a sua história</em></h2></div><a href="#como-funciona">Veja como funciona <ArrowRight/></a></div><div className="filter-row"><button className="active">Todos</button>{["Copos","Garrafas","Chaveiros","Camisetas","Kits"].map(x=><button key={x}>{x}</button>)}</div>
      <div className="product-grid">{products.map(p=><article className="product-card" key={p.id}><button className="product-visual" style={{"--tone":p.tone,"--accent":p.accent} as React.CSSProperties} onClick={()=>setSelected(p)}>{p.tag&&<span className="tag">{p.tag}</span>}<span className={`product-shape p${p.id}`}><b>{p.glyph}</b><small>Mimo & Arte</small></span><span className="quick">Personalizar <ArrowRight/></span></button><div className="product-info"><p>{p.category}</p><h3>{p.name}</h3><div><span>A partir de <b>{money(p.price)}</b></span><button onClick={()=>setSelected(p)} aria-label={`Personalizar ${p.name}`}><Plus/></button></div></div></article>)}</div>
    </section>
    <section className="how section" id="como-funciona"><div className="how-intro"><p className="eyebrow">Do seu jeito, sem complicação</p><h2>Como nasce<br/><em>o seu mimo</em></h2><p>Você conta a sua ideia. Nós cuidamos para que cada detalhe tenha significado.</p><div className="approval-card"><div><span>Arte V1</span><b>Aguardando aprovação</b></div><div className="mini-preview">M</div><div className="approval-line"><Check/> Prévia enviada para você</div><button>Aprovar arte</button></div></div><ol>{["Escolha seu produto","Conte como quer personalizar","Faça o pagamento","Aprovamos a arte com você","Produzimos seu pedido","Receba seu mimo"].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><b>{x}</b><ChevronRight/></li>)}</ol></section>
    <section className="gift-section" id="presentes"><div className="gift-visual"><div className="gift-box"><span/><b>M&A</b></div><p>embalado<br/>com carinho</p></div><div className="gift-copy"><p className="eyebrow"><Gift/> Para presentear</p><h2>Um presente que tem a cara de <em>quem você ama.</em></h2><p>Mais do que um objeto: uma lembrança criada para guardar afeto. Personalize nomes, frases, cores e temas.</p><button className="primary-cta" onClick={()=>setSelected(products[4])}>Criar um presente <ArrowRight/></button></div></section>
    <section className="discount-section"><div><p className="eyebrow">Boas-vindas à Mimo & Arte</p><h2>10% de carinho na sua primeira compra.</h2><p>Desconto automático em produtos a partir de R$ 150. Sem cupom.</p></div><span className="discount-badge"><b>10%</b><small>OFF</small></span></section>
    <footer id="contato"><div className="footer-main"><div><a className="brand light" href="#inicio"><span className="brand-mark">M</span><span>Mimo <i>&</i> Arte<small>Seu estilo em cada detalhe.</small></span></a><p>Personalizados que transformam detalhes em memórias.</p></div><div><b>Explore</b><a href="#inicio">Início</a><a href="#produtos">Produtos</a><a href="#como-funciona">Como funciona</a></div><div><b>Atendimento</b><span>WhatsApp a cadastrar</span><span>Instagram a cadastrar</span><span>E-mail a cadastrar</span></div><div><b>Informações</b><a href="#">Privacidade</a><a href="#">Termos de Uso</a><a href="#">Trocas e Devoluções</a></div></div><div className="footer-bottom"><span>© 2026 Mimo & Arte.</span><span>Dados comerciais serão inseridos pela proprietária.</span></div></footer>
    <button className="whatsapp" title="Número ainda não cadastrado"><span>☎</span><b>Fale com a Mimo & Arte</b></button>

    <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="customizer"><DialogHeader><DialogDescription>Personalize cada detalhe</DialogDescription><DialogTitle>Como você quer seu {selected?.name.toLowerCase()}?</DialogTitle></DialogHeader><div className="customizer-body"><div className="customizer-preview" style={{"--tone":selected?.tone,"--accent":selected?.accent} as React.CSSProperties}><span className="product-shape p2"><b>{name||"Seu nome"}</b><small>Mimo & Arte</small></span><small>Prévia ilustrativa. A arte final será enviada para aprovação.</small></div><div className="customizer-form"><div className="field"><Label>Cor</Label><Select value={color} onValueChange={setColor}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Chocolate">Chocolate</SelectItem><SelectItem value="Creme">Creme</SelectItem><SelectItem value="Dourado suave">Dourado suave</SelectItem></SelectContent></Select></div><div className="field"><Label>Nome ou frase</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Ana Clara" maxLength={40}/><small>{name.length}/40</small></div><div className="field"><Label>Conte sua ideia</Label><Textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Tema, estilo e detalhes que você imagina..."/></div><label className="upload-zone"><Upload/><span><b>Envie uma referência</b><small>JPG, PNG ou PDF • até 8 MB</small></span><Input type="file" accept=".jpg,.jpeg,.png,.pdf"/></label><div className="add-row"><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus/></button></div><Button onClick={add}>Adicionar • {selected&&money(selected.price*qty)}</Button></div></div></div></DialogContent></Dialog>
    <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-sheet"><SheetHeader><SheetTitle>Sua sacola <span>{cart.length}</span></SheetTitle><SheetDescription>Revise seus personalizados antes de continuar.</SheetDescription></SheetHeader>{!checkout?<><div className="cart-items">{cart.length===0?<div className="empty-cart"><ShoppingBag/><h3>Sua sacola está vazia</h3><p>Escolha uma peça e deixe-a com a sua cara.</p><Button onClick={()=>setCartOpen(false)}>Ver produtos</Button></div>:cart.map((item,i)=><div className="cart-item" key={`${item.id}-${i}`}><div className="cart-thumb" style={{background:item.tone}}>{item.glyph}</div><div><h4>{item.name}</h4><p>{item.color} • “{item.personalization}”</p><button onClick={()=>{setCartOpen(false);setSelected(item)}}>Revisar personalização</button><div className="cart-qty"><button onClick={()=>setCart(c=>c.map((x,j)=>j===i?{...x,qty:Math.max(1,x.qty-1)}:x))}><Minus/></button><span>{item.qty}</span><button onClick={()=>setCart(c=>c.map((x,j)=>j===i?{...x,qty:x.qty+1}:x))}><Plus/></button></div></div><b>{money(item.price*item.qty)}</b><button className="remove" onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><X/></button></div>)}</div>{cart.length>0&&<div className="cart-summary"><div className={subtotal>=150?"discount-progress unlocked":"discount-progress"}><div><Gift/><span><b>{subtotal>=150?"Você desbloqueou seu desconto!":`Faltam ${money(150-subtotal)} para liberar 10% OFF`}</b><small>Primeira compra • frete não incluso</small></span></div><Progress value={Math.min(100,subtotal/1.5)}/></div><dl><div><dt>Subtotal</dt><dd>{money(subtotal)}</dd></div>{discount>0&&<div className="green"><dt>Desconto</dt><dd>− {money(discount)}</dd></div>}<div><dt>Frete SP</dt><dd>{money(shipping)}</dd></div><div className="total"><dt>Total</dt><dd>{money(total)}</dd></div></dl><Button className="checkout-btn" onClick={()=>setCheckout(true)}>Ir para o checkout <ArrowRight/></Button><small className="secure"><ShieldCheck/> Pagamento seguro via PIX ou débito</small></div>}</>:<Checkout total={total} onBack={() => { setCheckout(false); }}/>}</SheetContent></Sheet>
  </main>;
}

function Checkout({total,onBack}:{total:number;onBack:()=>void}){const[payment,setPayment]=useState("pix");return <div className="checkout"><button className="back" onClick={onBack}>← Voltar à sacola</button><h3>Finalizar pedido</h3><Tabs defaultValue="delivery"><TabsList><TabsTrigger value="delivery">1. Entrega</TabsTrigger><TabsTrigger value="payment">2. Pagamento</TabsTrigger></TabsList><TabsContent value="delivery" className="checkout-form"><Label>Nome completo<Input placeholder="Seu nome"/></Label><Label>WhatsApp<Input placeholder="(11) 99999-9999"/></Label><Label>E-mail<Input type="email" placeholder="voce@exemplo.com"/></Label><Label>CEP<Input inputMode="numeric" placeholder="00000-000"/></Label><p className="legal-note">Seus dados serão usados apenas para produzir, entregar e acompanhar o pedido.</p></TabsContent><TabsContent value="payment"><div className="payment-options"><button className={payment==="pix"?"selected":""} onClick={()=>setPayment("pix")}><span>PIX</span><small>Confirmação automática</small><Check/></button><button className={payment==="debit"?"selected":""} onClick={()=>setPayment("debit")}><span>Cartão de débito</span><small>Processado pelo PagBank</small><Check/></button></div><div className="payment-total"><span>Total</span><b>{money(total)}</b></div><Button disabled>Pagamento disponível após configurar o PagBank</Button><p className="legal-note">Nenhuma cobrança será criada nesta prévia.</p></TabsContent></Tabs></div>}




